---

services:
  vaultwarden:
    image: vaultwarden/server:1.34.2
    restart: unless-stopped
    depends_on:
      - pgsql
    networks:
      - vw-net
      - traefik_default
    dns:
      - 1.1.1.1
      - 9.9.9.9
    volumes:
      - vaultwarden_data:/data
    environment:
      DOMAIN: "https://${VAULTWARDEN_HOST}"
      SIGNUPS_ALLOWED: "true"
      ENABLE_DB_WAL: "false"
      DATABASE_URL: "postgresql://${PG_USER}:${PG_PASSWORD}@pgsql/${PG_DB}"
      # Temporary password: UseCyberchefToCreateArgo2
      ADMIN_TOKEN: $$argon2i$$v=19$$m=4096,t=3,p=1$$c29tZXNhbHQ$$Eq9NviMVO34U91CeCixnI9zybZJZXWS05EvJBpgNBuE
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.vaultwarden-https.rule=Host(`${VAULTWARDEN_HOST}`)
      - traefik.http.routers.vaultwarden-https.entrypoints=https
      - traefik.http.routers.vaultwarden-https.tls=true
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
    logging:
      driver: none

  pgsql:
    image: postgres:16.10-alpine
    restart: always
    networks:
      - vw-net
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - vaultwarden_pgsqldata:/var/lib/postgresql/data
    logging:
      driver: none

networks:
  vw-net:
  traefik_default:
    external: true

volumes:
  vaultwarden_pgsqldata:
    external: true
  vaultwarden_data:
    external: true