networks:
  gitea:
  traefik_default:
    external: true

volumes:
  gitea_data:
    external: true
  gitea_db:
    external: true

services:
  server:
    image: gitea/gitea:1.23.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=${GITEA_DB_TYPE}
      - GITEA__database__HOST=${GITEA_DB_HOST}:5432
      - GITEA__database__NAME=${GITEA_DB_NAME}
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD}
    restart: always
    networks:
      - gitea
      - traefik_default
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    #ports:
    #  - "3000:3000"
    #  - "222:22"
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.gitea-https.rule=Host(`${GITEA_HOST}`)
      - traefik.http.routers.gitea-https.entrypoints=https
      - traefik.http.routers.gitea-https.tls=true
      - traefik.http.services.gitea.loadbalancer.server.port=3000


  db:
    image: postgres:16.10-alpine
    restart: always
    environment:
      - POSTGRES_USER=${GITEA_DB_USER}
      - POSTGRES_PASSWORD=${GITEA_DB_PASSWORD}
      - POSTGRES_DB=${GITEA_DB_NAME}
    networks:
      - gitea
    volumes:
      - gitea_db:/var/lib/postgresql/data